create table if not exists public.opinions (
  id bigint generated by default as identity primary key,
  name text not null,
  ideas text[] not null,
  created_at timestamptz not null default now()
);

alter table public.opinions enable row level security;

create policy if not exists "Allow insert for anyone"
on public.opinions
for insert
with check (true);

create policy if not exists "Allow read for anyone"
on public.opinions
for select
using (true);
